# Generated by Django 3.2.2 on 2021-05-27 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55)),
                ('quantity', models.IntegerField()),
                ('price', models.FloatField()),
                ('discount', models.FloatField()),
            ],
        ),
    ]
