# Generated by Django 3.2.2 on 2021-06-03 17:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0003_auto_20210531_1923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='qty',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(20)]),
        ),
    ]
