# Generated by Django 3.2.2 on 2021-06-03 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0004_alter_order_qty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='part',
        ),
        migrations.AddField(
            model_name='order',
            name='parts',
            field=models.ManyToManyField(to='purchase.Stock'),
        ),
    ]
