# Generated by Django 3.2.2 on 2021-05-23 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_pizza_isactive'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pizza',
            name='size',
        ),
    ]
