# Generated by Django 3.2.2 on 2021-05-23 21:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_remove_pizza_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('your_name', models.CharField(max_length=100)),
                ('date_time', models.DateTimeField(default=datetime.datetime.now)),
                ('address', models.CharField(max_length=255)),
            ],
        ),
    ]
