# Generated by Django 3.2.3 on 2021-05-28 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('salesman', models.BooleanField()),
                ('manager', models.BooleanField()),
                ('photo', models.ImageField(upload_to='photo/%Y/%m/%d/')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=255)),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cashier', to='employees.employee')),
                ('worker2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boulangerie', to='employees.employee')),
                ('worker3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mainsalesman', to='employees.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Timetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField()),
                ('is_working_day', models.BooleanField()),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.team')),
            ],
        ),
    ]
