# Generated by Django 3.2.3 on 2021-05-22 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizza',
            name='engname',
            field=models.CharField(default=False, max_length=255),
            preserve_default=False,
        ),
    ]
