# Generated by Django 3.2.3 on 2021-05-23 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_ingredient'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizza',
            name='ingredients',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='stock.ingredient'),
            preserve_default=False,
        ),
    ]
