# Generated by Django 3.2.3 on 2021-05-23 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0004_pizza_ingredients'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pizza',
            name='ingredients',
        ),
        migrations.AddField(
            model_name='pizza',
            name='ingredients',
            field=models.ManyToManyField(to='stock.Ingredient'),
        ),
    ]
