# Generated by Django 3.2.3 on 2021-05-24 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0006_auto_20210524_1409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizza',
            name='comment',
            field=models.TextField(default=''),
        ),
    ]
