# Generated by Django 3.2.3 on 2021-05-25 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0008_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopingCar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.CharField(max_length=255)),
                ('adress', models.CharField(max_length=255)),
                ('time', models.TimeField()),
                ('date', models.DateField()),
                ('food', models.ManyToManyField(to='stock.Order')),
            ],
        ),
    ]
