# Generated by Django 3.2.3 on 2021-05-25 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0009_shopingcar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopingcar',
            name='food',
        ),
    ]
