# Generated by Django 3.2.3 on 2021-05-25 19:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0010_remove_shopingcar_food'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopingcar',
            name='food',
            field=models.ForeignKey(blank=True, default=False, on_delete=django.db.models.deletion.CASCADE, to='stock.order'),
            preserve_default=False,
        ),
    ]
