# Generated by Django 3.2.3 on 2021-05-25 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0011_shopingcar_food'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopingcar',
            name='food',
        ),
        migrations.AddField(
            model_name='shopingcar',
            name='food',
            field=models.ManyToManyField(to='stock.Order'),
        ),
    ]
