# Generated by Django 3.2.3 on 2021-05-20 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizza',
            name='active_field',
            field=models.BooleanField(default=True),
        ),
    ]
