# Generated by Django 3.2.2 on 2021-05-26 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_orderpizza'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderpizza',
            name='created_at',
        ),
    ]
