# Generated by Django 3.2.2 on 2021-05-26 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0004_remove_orderpizza_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderpizza',
            name='created_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата создания заказа'),
        ),
    ]
