# Generated by Django 3.2.2 on 2021-05-26 19:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0007_orderpizza_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderpizza',
            name='created_at',
        ),
        migrations.AddField(
            model_name='orderpizza',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
