# Generated by Django 3.2.2 on 2021-05-16 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pizza',
            old_name='mane',
            new_name='name',
        ),
    ]
