# Generated by Django 3.2.2 on 2021-05-16 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_rename_mane_pizza_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizza',
            name='submitted',
            field=models.BooleanField(default=False),
        ),
    ]
