# Generated by Django 3.2.2 on 2021-05-16 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_pizza_submitted'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pizza',
            old_name='submitted',
            new_name='active',
        ),
    ]
