# Generated by Django 3.2.2 on 2021-05-23 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_pizza_submitted'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreatePizza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=30)),
                ('description', models.TextField(blank=True, max_length=255)),
                ('checked', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('size', models.CharField(max_length=20)),
                ('weight', models.IntegerField()),
                ('author', models.CharField(blank=True, max_length=30)),
                ('comment', models.TextField(blank=True, max_length=255)),
            ],
        ),
        migrations.RenameField(
            model_name='pizza',
            old_name='submitted',
            new_name='active',
        ),
        migrations.AlterField(
            model_name='pizza',
            name='size',
            field=models.CharField(max_length=20),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('date', models.DateTimeField()),
                ('address', models.TextField(max_length=255)),
                ('quantity', models.PositiveSmallIntegerField(default=0)),
                ('choice', models.ManyToManyField(to='stock.Pizza')),
            ],
        ),
    ]
