# Generated by Django 3.2.2 on 2021-05-24 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0005_auto_20210523_2143'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='size',
            field=models.CharField(choices=[('s', 'small'), ('m', 'medium'), ('l', 'large'), ('xl', 'x-large')], default='m', max_length=300),
            preserve_default=False,
        ),
    ]
