# Generated by Django 3.2.2 on 2021-05-20 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0006_alter_pizza_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizza',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
