# Generated by Django 3.2.2 on 2021-05-27 19:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_order_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='price',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.clients'),
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField(default=0)),
                ('choice_text', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.product')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.order')),
            ],
        ),
    ]
