# Generated by Django 3.2.2 on 2021-05-12 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizza',
            name='active',
            field=models.BooleanField(default=True, verbose_name=True),
            preserve_default=True,
        ),
    ]
