# Generated by Django 3.2.2 on 2021-05-12 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_pizza_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizza',
            name='active',
            field=models.BooleanField(verbose_name=True),
        ),
    ]
