# Generated by Django 3.2.2 on 2021-05-12 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0004_pizza_info'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pizza',
            name='info',
        ),
        migrations.AlterField(
            model_name='pizza',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
