# Generated by Django 3.2.2 on 2021-05-12 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_alter_pizza_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizza',
            name='info',
            field=models.CharField(default='add additional info', max_length=255),
        ),
    ]
