# Generated by Django 3.2.2 on 2021-05-12 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizza',
            name='isActive',
            field=models.BooleanField(default=True),
        ),
    ]
