# Generated by Django 3.2.2 on 2021-05-23 22:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0004_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='pizza',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='stock.pizza'),
            preserve_default=False,
        ),
    ]
