# Generated by Django 3.2.2 on 2021-05-23 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0005_order_pizza'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomPizza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auth_name', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(max_length=255)),
                ('weight', models.IntegerField()),
                ('isConfirmed', models.BooleanField(default=False)),
            ],
        ),
    ]
